export const CARD_LIST_REQUEST = "CARD_LIST_REQUEST";
export const CARD_LIST_SUCCESS = "CARD_LIST_SUCCESS";
export const CARD_LIST_FAIL = "CARD_LIST_FAIL";

export const CARD_ADD_COMMENT = "CARD_ADD_COMMENT";
export const CARD_ADD_LIKE = "CARD_ADD_LIKE";
